webdriver.driver=firefox
headless.mode=true
serenity.project.name=Reto 2 - Automatizacion E2E SauceDemo con Serenity BDD
serenity.take.screenshots=AFTER_EACH_STEP
serenity.reports.show.step.details=true